ACCESS_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJCLXI1cVdTTlVKWkM4aXpkVmNHUW1QMk5xWHJLSm1hbjdYTExIWjJOMzZVIn0.eyJleHAiOjE3ODA3MzQwMzksImlhdCI6MTc4MDczMzczOSwianRpIjoib25ydHJvOjJjNWQzYTBhLTM0NGQtNGYxMS0zNWY5LWYwNzU0ZjE1ZDA4NyIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9yZWFsbXMvYWJhYy1yZWFsbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIzNDNkZjI3OC0xZWI2LTRlNGYtOThiZi01MDExMzZkZTE4YmEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJkb2N1bWVudC1zZXJ2aWNlLWFwaSIsInNpZCI6Ik5ld0RTdzJTTmY2V3hyVFlBcFNkSHkyaiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWFiYWMtcmVhbG0iLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImNsZWFyYW5jZV9sZXZlbCI6IjMiLCJuYW1lIjoiQWxpY2UgU21pdGgiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbGljZSIsImdpdmVuX25hbWUiOiJBbGljZSIsImRlcGFydG1lbnQiOiJociIsImZhbWlseV9uYW1lIjoiU21pdGgiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIn0.kErVd55TodzPwr4FmuiwZtvFhDfoY_NxF0vjxbtX9kTSslthHPHHrf4pMFPo4mM9qM9AgR1aYK9evDSBtXBGN4eJbBYsQjHBIP0fp7pQ56b3_Dnhq2ukERuvKVWE6a7NjMGYdvdegyaYDcGer6_hF28wzej93XKb-BxQRWn0RNHt_fNQEUsxHRPZom7sXn9KUptfbpEwFWvGhIRHiX7afx4TgVFZRRrJ5NUjWrV6_xID6ultYwhN4qCjGinS4_JJBDuArpE1lz7hRhEPfqNX-b9Ye-0qVGpS1sQT51xWax4VQyTQSoW7GDdSoHIu52w3Ha03kjLRouW7Fvmy3Zv0dg"

CLAIM_TOKEN=$(printf '%s' '{"network_location":["office"]}' | base64 -w0)
curl -H "Authorization: Bearer ${ACCESS_TOKEN}" \
     -d "grant_type=urn:ietf:params:oauth:grant-type:uma-ticket" \
     -d "audience=document-service-api" \
     -d "response_mode=decision" \
     -d "permission=Secret HR Report" \
     -d "claim_token=${CLAIM_TOKEN}" \
     -d "claim_token_format=urn:ietf:params:oauth:token-type:jwt" \
     -X POST http://localhost:8080/realms/abac-realm/protocol/openid-connect/token
