ACCESS_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJCLXI1cVdTTlVKWkM4aXpkVmNHUW1QMk5xWHJLSm1hbjdYTExIWjJOMzZVIn0.eyJleHAiOjE3ODA3MzQxOTcsImlhdCI6MTc4MDczMzg5NywianRpIjoib25ydHJvOmM1YjhmOGRhLTM5YjUtODgzNi1iZWFlLWU5MzFhZjg1ZmI3MyIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9yZWFsbXMvYWJhYy1yZWFsbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIzNDNkZjI3OC0xZWI2LTRlNGYtOThiZi01MDExMzZkZTE4YmEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJkb2N1bWVudC1zZXJ2aWNlLWFwaSIsInNpZCI6ImVmVUl6OVdLc1FwVWlGZWQ2Um5lNHNseiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWFiYWMtcmVhbG0iLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImNsZWFyYW5jZV9sZXZlbCI6IjMiLCJuYW1lIjoiQWxpY2UgU21pdGgiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbGljZSIsImdpdmVuX25hbWUiOiJBbGljZSIsImRlcGFydG1lbnQiOiJociIsImZhbWlseV9uYW1lIjoiU21pdGgiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIn0.FE11gwm5oNZfVM46Kj2EUKvEqRGItqzoB5UuKWJQtAcH_rJUn3c04QCx6UlkynOZ-eDkwKo-x1RYRgExY1fvqWC0VH8TJPxC5YZhIFa7ZAG83BqSvUZli_dtTVWLqehAjNcZqR1kFPUgPMOTIg7OLVDRpkAMulwwbcLJTeq2RzBB1UVc_5ezxVcK9jEOgR9ASsZB-UpXf54JeH8PiKGk4Ed2PjjklEaC5Jjv5pWea7d8UooXwtaOo8P-mbnJIOyrCgtGTwEQKs1XU-psa9-172yANwfeF29bNigAgukvr7W_jFbh9DxMmXxoUyy4DSNFUD8TOTmt1QDJ3G6eO2vz7A"

CLAIM_TOKEN=$(printf '%s' '{"network_location":["office"]}' | base64 -w0)
curl -H "Authorization: Bearer ${ACCESS_TOKEN}" \
     -d "grant_type=urn:ietf:params:oauth:grant-type:uma-ticket" \
     -d "audience=document-service-api" \
     -d "permission=Secret HR Report" \
     -d "claim_token=${CLAIM_TOKEN}" \
     -d "claim_token_format=urn:ietf:params:oauth:token-type:jwt" \
     -X POST http://localhost:8080/realms/abac-realm/protocol/openid-connect/token
