ACCESS_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJCLXI1cVdTTlVKWkM4aXpkVmNHUW1QMk5xWHJLSm1hbjdYTExIWjJOMzZVIn0.eyJleHAiOjE3ODA3Mzc2OTUsImlhdCI6MTc4MDczNzM5NSwianRpIjoib25ydHJvOmJkZGQzMDEyLWIzNTUtMWJjMC0wY2Q4LWJhMjc1MGNhMzdjZCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9yZWFsbXMvYWJhYy1yZWFsbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIzNDNkZjI3OC0xZWI2LTRlNGYtOThiZi01MDExMzZkZTE4YmEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJkb2N1bWVudC1zZXJ2aWNlLWFwaSIsInNpZCI6InJCM205U3QxYmp6aWRuQTJLNW5BMjdPeiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWFiYWMtcmVhbG0iLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImNsZWFyYW5jZV9sZXZlbCI6IjMiLCJuYW1lIjoiQWxpY2UgU21pdGgiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbGljZSIsImdpdmVuX25hbWUiOiJBbGljZSIsImRlcGFydG1lbnQiOiJociIsImZhbWlseV9uYW1lIjoiU21pdGgiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIn0.Jsz8zkoSkce6ZnpjOMlCOKU2cV2hIXw2tu0yeq5OzNkw97PkXzqh59PbdgWk4lrfhcrJPEt4usH9ieUhSAZXwhLsBv3nRozOsXgujn86kPQNECtn5xT2R7k0UXx5fzVbTAQ2vxfqGlLbiOIIBe42YyHYYYaBNdNXxuqRWZLoKvv2tHsXPHVsW9KOfSPVW4dhD38YugGf256cxc7po8pua_-Bxvk_Vszm6U8KNgo_3TZjSaePXrakpJJCwnEt2PpUjPP6c3NmitvqoMLQZelI72JonhgagQ1nvZlYni-v1OmIDCENZZ5ZGGlKrCVNE5s5Yw0a5jgkm6TMCqRjaWsOwA"

CLAIM_TOKEN=$(printf '%s' '{"network_location":["office"]}' | base64 -w0)
curl -H "Authorization: Bearer ${ACCESS_TOKEN}" \
     -d "grant_type=urn:ietf:params:oauth:grant-type:uma-ticket" \
     -d "audience=document-service-api" \
     -d "response_mode=decision" \
     -d "permission=Secret HR Report" \
     -d "claim_token=${CLAIM_TOKEN}" \
     -d "claim_token_format=urn:ietf:params:oauth:token-type:jwt" \
     -X POST http://localhost:8080/realms/abac-realm/protocol/openid-connect/token
